import type { Metadata } from "next";
import {DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import NavContextComponent from "./components/navContext";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "900"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="js-focus-visible" data-js-focus-visible="">
      <body className={`${dmSans.variable} antialiased`} >
        <NavContextComponent>
          <Navbar />
          {children}
          <Footer />
        </NavContextComponent>
      </body>
    </html>
  );
}
